---
- hosts: all
  sudo: yes

  tasks:
  ##
   # Instalaci贸n de paquetes necesarios.
  ##
   - name: General | Instalaci贸n de paquetes requeridos.
     action: apt pkg={{ item }} state=installed
     with_items:
     - apache2
     - mysql-client
     - mysql-server
     - php7.0
     - libapache2-mod-php7.0
  
  ##
   # Configuraci贸n de Apache2.
  ##
   - name: Apache2 | Habilitar m贸dulos
     action: command a2enmod rewrite vhost_alias
